name: Create release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install node dependencies
        run: pnpm install --prod

      - name: Build frontend assets
        run: pnpm build

      - name: Create Release Archive
        run: |
          zip -r "Lattebooru_${{ github.ref_name }}.zip" . \
            -x ".editorconfig" \
            -x ".env" \
            -x ".github/*" \
            -x ".prettierrc" \
            -x "*.git*" \
            -x "node_modules/*" \
            -x "package.json" \
            -x "phpunit.xml" \
            -x "pnpm-lock.yaml" \
            -x "postcss.config.js" \
            -x "resources/css/*"
            -x "resources/js/*" \
            -x "shell.nix" \
            -x "tailwind.config.js" \
            -x "tests/*" \
            -x "vite.config.js" \

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: "Lattebooru_${{ github.ref_name }}.zip"
          name: Latebooru ${{ github.ref_name }}
          body: |
            ## Latebooru ${{ github.ref_name }}

            ### Installation
            1. Download and extract the release.zip
            2. Run `composer install --no-dev`
            3. Configure your `.env` file (there's a .env.example included)
            4. Run migrations if needed: `php artisan migrate`

            The frontend assets are pre-compiled and included in the `public/build` directory.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
